import {
  ApplicationActions,
  ISetHighScoreElims,
  ISetHighScoreOverall,
  ISetHighScoreQuals,
  ISetTotalEventSize,
  ISetTotalTeamSize,
  ISetTotalMatchSize,
  ISetTeams,
  ISetMatches,
  ISetEvents,
  ISetRegions,
  ISetSeasons,
  setHighScoreElims,
  setHighScoreOverall,
  setHighScoreQuals,
  setTotalEventSize,
  setTotalMatchSize,
  setTotalTeamSize,
  setTeams,
  setMatches,
  setEvents,
  setRegions,
  setSeasons,
  setEventData,
  setEventMatches,
  setEventRankings,
  setEventInsights
} from "./stores/Actions";
import * as Types from "./stores/Types";
import {
  IApplicationState,
  IApplicationStateJSON,
  IHighestScoringMatches,
  IHighestScoringMatchesJSON
} from "./stores/Types";
import Reducer, { defaultState } from "./stores/Reducer";
import TOAProvider from "./providers/TOAProvider";

import { IHomeProps, ITeamsProps, IEventsProps, IRegionProps, ISeasonProps } from "./PageProperties";
import {
  getHomeData,
  getTeamsData,
  getEventsData,
  getEventData,
  getEventMatches,
  getEventRankings,
  getEventInsights,
  getEventAwards,
  getRegionsData,
  getSeasonsData
} from "./PageData";

export {
  ApplicationActions,
  ISetHighScoreElims,
  ISetHighScoreOverall,
  ISetHighScoreQuals,
  ISetTotalEventSize,
  ISetTotalTeamSize,
  ISetMatches,
  ISetTeams,
  ISetEvents,
  ISetRegions,
  ISetSeasons,
  setHighScoreElims,
  setHighScoreOverall,
  setHighScoreQuals,
  setTotalEventSize,
  setTotalTeamSize,
  setTotalMatchSize,
  setTeams,
  setMatches,
  setEvents,
  setRegions,
  setSeasons,
  Types,
  Reducer,
  defaultState,
  IApplicationState,
  IApplicationStateJSON,
  IHighestScoringMatches,
  IHighestScoringMatchesJSON,
  TOAProvider,
  IHomeProps,
  ITeamsProps,
  IEventsProps,
  IRegionProps,
  ISeasonProps,
  getHomeData,
  getTeamsData,
  getEventsData,
  getEventData,
  setEventData,
  getSeasonsData,
  getRegionsData,
  getEventMatches,
  setEventMatches,
  getEventRankings,
  setEventRankings,
  getEventInsights,
  setEventInsights
};
